resources:
  - name: jatin_gitRepo
    type: GitRepo
    configuration:
      gitProvider: jatin_gh
      path: jatindogra/demo-extenstions
      branches:
        include: ^main$
 
  - name: extension_resource
    type: playbook/gitrepo
    syntaxVersion: latest
    configuration:      
      GitHub : jatin_gh
      gitUrl: "https://github.com/jatindogra/demo-extenstions.git"
      gitBranch: main
      

pipelines:
  - name: extensions_pipelines
    steps:
      - name: extension_step
        type: playbook/ansible
        syntaxVersion: latest
        configuration:              
          foo: bar
          inputResources:
            - name: extension_resource
            - name: jatin_gitRepo
        execution:
          onStart:
            - echo "Preparing for work..."
